### ISSUE TITLE
Review open PRs, pull in all salvageable work

### ISSUE THREAD

**Issue by lalalune** [webaverse-studios/app#17]
Now that we have Labs and Studios, we need to clean up and deal with all of the open PRs.

We should review these, see which ones haven't been merged, make a list of the ones that are good to go and either merge them or get the creators to merge.

Anything stale should be closed in webaverse/app.

https://github.com/webaverse/app/pull/3648
https://github.com/webaverse/app/pull/3627
https://github.com/webaverse/app/pull/3701
https://github.com/webaverse/app/pull/3548
https://github.com/webaverse/app/pull/3567
https://github.com/webaverse/app/pull/3665
https://github.com/webaverse/app/pull/3663
https://github.com/webaverse/app/pull/3666
https://github.com/webaverse/app/pull/3673
https://github.com/webaverse/app/pull/3638
https://github.com/webaverse/app/pull/3637
https://github.com/webaverse/app/pull/3635
https://github.com/webaverse/app/pull/3633
https://github.com/webaverse/app/pull/3600
https://github.com/webaverse/app/pull/3681
https://github.com/webaverse/app/pull/3691
https://github.com/webaverse/app/pull/3697
https://github.com/webaverse/app/pull/3700
https://github.com/webaverse/app/pull/3715
https://github.com/webaverse/app/pull/3717
https://github.com/webaverse/app/pull/3720
https://github.com/webaverse/app/pull/3385

Definitely need some review
https://github.com/webaverse/app/pull/3710
https://github.com/webaverse/app/pull/3713
https://github.com/webaverse/app/pull/3711
https://github.com/webaverse/app/pull/3714
https://github.com/webaverse/app/pull/3337
https://github.com/webaverse/app/pull/3327

I think these were merged, but should review
https://github.com/webaverse/app/pull/3722
https://github.com/webaverse/app/pull/3721
https://github.com/webaverse/app/pull/3708
https://github.com/webaverse/app/pull/3688
https://github.com/webaverse/app/pull/3686
https://github.com/webaverse/app/pull/3685
https://github.com/webaverse/app/pull/3654
https://github.com/webaverse/app/pull/3540
https://github.com/webaverse/app/pull/3618
https://github.com/webaverse/app/pull/3616
https://github.com/webaverse/app/pull/3651
https://github.com/webaverse/app/pull/3647

**Comment by belopot** [comment]
Following PRs were reviewed and merged
https://github.com/webaverse/app/pull/3710
https://github.com/webaverse/app/pull/3713
