### ISSUE TITLE
[REVIEW] Make sure all of webaverse main branch three-vrm upgrades are also in studios/three-vrm

### ISSUE THREAD

**Issue by lalalune** [webaverse-studios/app#18]
I updated https://github.com/webaverse-studios/three-vrm and corresponding repos to 1.0.2, since VRM is officially out of beta.

I merged in one of Avaer's optimizations but wasn't clear on all of them. VRM 1.0 seems to have async loading, which is a lot of what he was doing.

I set up the repos to build from source, so that we can modify the source and rebuild the libraries intead of just modifying the library outputs.

The task here is that we need to go through Avaer's changes and make sure all of the optimizations were brought in and checked, so that we can permanently update to 1.0, put it into production, update all of our avatars and push back to main webaverse/app.

**Comment by belopot** [comment]
I've reviewed this issue. There were no problems. We keep to use VRM0 for now.

**Comment by belopot** [comment]
https://github.com/webaverse-studios/pixiv-three-vrm
This repo includes all source code for VRM. we can customize it and build every package
