### ISSUE TITLE
Fix issue that equipment cards were not generated 

### ISSUE THREAD

**Issue by belopot** [webaverse-studios/app#59]
**Describe the bug**
Issue that equipment cards were not generated

**To Reproduce**
![image](https://user-images.githubusercontent.com/46432435/194333584-7b9c1c6b-97cb-4f3c-9475-d7820b54aed6.png)

**Comment by hedera07** [comment]
I fixed this issues before.
So I push that updates again.
This issue was caused by the return value of generateStats in procgen/stats.js.
I push a PR for this : https://github.com/webaverse-studios/app/pull/66

**Comment by belopot** [comment]
Great!
